### ISSUE TITLE
Sync Last Added

### ISSUE THREAD

**Issue by screwfaze** [jmshrv/finamp#101]
Please add an option to download latest albums added to jellyfin automatically.

Thanks

**Comment by UnicornsOnLSD** [comment]
I'll look into adding a button for it somewhere :)

**Comment by screwfaze** [comment]
> I'll look into adding a button for it somewhere :)

Thanks mate really loving the app keep up the good work

**Comment by Chaphasilor** [comment]
@screwfaze the download system has been improved as part of the redesign beta. There's now an option in the download settings to automatically download the 5 latest albums (and keep them up-to-date). This will be improved upon with future updates (e.g. selecting how many albums you want to download). You can check it out here: https://github.com/jmshrv/finamp/releases/tag/0.9.2-beta

I'll close this issue for now since it should be resolved.
