### ISSUE TITLE
Artist Tab Margin to small

### ISSUE THREAD

**Issue by kjboa** [jmshrv/finamp#123]
Hi, First of thank you for creating this awesome app it really has simplified my music streaming a lot. One small thing however bugs me: in the artist Tab there is no margin between the different artists, same thing with the genres tab. I'm not sure if this is a design choice but I think it looks a little odd.

I tested this on two different Android phones and both showed the same results.

Artists tab:

![Screenshot_2021-09-05-13-39-26-43_bd089574a79f02629f0e15c227aed74a.jpg](https://user-images.githubusercontent.com/65646265/132125754-1beb54cf-5498-491b-b705-37ced2217120.jpg)

**Comment by UnicornsOnLSD** [comment]
Yeah it annoys me too. I tried to add the number of albums below the artist name but Jellyfin wasn't giving it to me for some reason. I'll probably try again at some point.

**Comment by Mandeep56Singh** [comment]
I would like to work on this one

**Comment by Mandeep56Singh** [comment]
can you please help in setup for this project ?

**Comment by Chaphasilor** [comment]
@Mandeep56Singh of course! Generally the steps are as follows:
1. Install Flutter & set up your preferred editor (https://docs.flutter.dev/get-started/install)  
   - Follow the guide until the chapter "Test Drive" (inclusive)
2. Make sure Git is installed. If not, search online on how to install it
3. Clone the Finamp repository into a directory like `Documents` or `Code`. The command is `git clone https://github.com/jmshrv/finamp`
4. Open the newly created `finamp` folder with your editor (i.e. VS Code)
5. If you editor is configured correctly, it should detect Finamp's Flutter project automatically
6. Attach your phone via USB (and allow USB debugging)
7. "Build" the project, this should automatically generate all files and launch the Finamp app on your phone  
   - You might have to uninstall Finamp from your phone first, because your computer will use a different unique signature than @jmshrv's

That should be it, but maybe @jmshrv can add some other things I might have missed :)

**Comment by Mandeep56Singh** [comment]
thanks a lot  @Chaphasilor

**Comment by Mandeep56Singh** [comment]
@Chaphasilor 
sorry for late response , 
I having problem passing the first screen , how to set server , username and password ?
Really sorry for this dumb question , actually i have not use any jellyphin service before.

**Comment by jmshrv** [comment]
Do you have a Jellyfin server? You'd use the URL you use to access it, and your username/password.

**Comment by Mandeep56Singh** [comment]
@jmshrv  no I don't have Jellyfin server

**Comment by jmshrv** [comment]
Ah, well you could use the demo server by doing:

Server URL: `https://demo.jellyfin.org/stable`
Username: `demo`
And leave password blank

Note that the demo server gets wiped every hour, so you'll have to sign in again each hour.

Just wondering, if you don't have a Jellyfin server, what's made you want to contribute to Finamp?

**Comment by Mandeep56Singh** [comment]
![WhatsApp Image 2023-10-08 at 2 19 23 PM](https://github.com/jmshrv/finamp/assets/139469106/ad6a7144-a600-4f85-914a-88ebfe5f8f0f)
I have solved the artist sections 
but when I try to give padding to genre section , the albums sections padding increases

**Comment by Chaphasilor** [comment]
Yeah that's because the `AlbumListTile` is also used for genres. You could copy into a separate `GenreListTile` and use that instead?

https://github.com/jmshrv/finamp/blob/main/lib/components/MusicScreen/music_screen_tab_view.dart#L378-L391

**Comment by Mandeep56Singh** [comment]
ok

**Comment by Mandeep56Singh** [comment]
> Yeah that's because the `AlbumListTile` is also used for genres. You could copy into a separate `GenreListTile` and use that instead?
> 
> https://github.com/jmshrv/finamp/blob/main/lib/components/MusicScreen/music_screen_tab_view.dart#L378-L391

can you help me how to do it ?

**Comment by Mandeep56Singh** [comment]
> Yeah that's because the `AlbumListTile` is also used for genres. You could copy into a separate `GenreListTile` and use that instead?
> 
> https://github.com/jmshrv/finamp/blob/main/lib/components/MusicScreen/music_screen_tab_view.dart#L378-L391

can you help me how to do it ?

**Comment by Chaphasilor** [comment]
Sorry, didn't see your response. You need to rename all the classes that you copied into the new file, so that it says
`class GenreListTile` instead of `class AlbumListTile`, and so on. Then you can import the new file within the genre list, by adding an import at the top of the file. There should be an import for `AlbumListTile` already, just duplicate it and change the file path :)

**Comment by Chaphasilor** [comment]
@kjboa this has been fixed as part of the redesign beta (maybe it's also in the stable version already?). You can check it out here: https://github.com/jmshrv/finamp/releases/tag/0.9.2-beta

I'll close this issue for now since it should be resolved.
