### ISSUE TITLE
[Feature Request] Codec, Bitrate, Sample Rate on Player Screen

### ISSUE THREAD

**Issue by seniorm0ment** [jmshrv/finamp#184]
Requesting ability to see the codec, bitrate, sample rate. As well as next to the albums and tracks on the main tabs when scrolling.
This also helps differentiate between the same albums with different codecs, bit/samplerates.

And on the now playing page, the album art seems very high comlared to the buttons, and the buttons, seekbar, and seekbar have very large gaps vertically between each other. 

Title font is also very large.

No way to click on the artist, or see the name of the album playing.

**Comment by UnicornsOnLSD** [comment]
I could look into showing the bitrate and stuff on the main pages, although it might start to get cluttered since that could be a lot of information. I'm definitely going to add it to the player screen at some point though.

The new update adds an app bar to the player screen so everything becomes a bit less far apart. The title font looks fine to me, but you could argue that it's small in relation to the album/artist names. Adding the ability to click on the album/artist name shouldn't be too hard.

![image](https://user-images.githubusercontent.com/44349936/149922516-0bbea84f-f6dd-4788-8e1c-c13982f49761.png)

**Comment by seniorm0ment** [comment]
Not sure how open you are to making stuff optional, but it could just be a toggle to show it on the other menus.

As well as the title font, it's fine there, but when you have long titles it really just squishes in. It would be nice to adjust it down maybe 2-3 sizes. Or at least give the user the option too.

**Comment by seniorm0ment** [comment]
Poweramp has a nice interface that you can reference for the codec/bitrate info placement. Or to get an idea.
https://powerampapp.com/

May also want to browse some of Poweramps other features to see if anything can be added to improve Finamp, it's quite a powerhouse player. Replaygain would be a nice feature. Not sure if Jellyfin supports that though. :)

**Comment by StyraxBenzoin** [comment]
I too would like to see the codec and bitrate on the now playing screen. Perhaps next to or under the 'Direct Streaming' text.

**Comment by UnicornsOnLSD** [comment]
Update on requests in this issue:

* Song file info is dependant on the audio plugin supporting it, there is an open issue for it with some good info: https://github.com/ryanheise/just_audio/issues/509
* Spacing has been fixed as of 0.6.0
* Title font issue still stands, I'll think about it
* Clicking on artist/album has been added

I'm going to rename this issue to focus on the song file info so that I can more easily find it in the future

**Comment by othyn** [comment]
I would love to see this. Its one of the main things I'm missing from PlexAmp!

**Comment by Chaphasilor** [comment]
It seems like Jellyfin doesn't give us the sample rate, but I've added codec, bitrate and file size for the next beta update!

**Comment by othyn** [comment]
Thank you so much, thats awesome!
