### ISSUE TITLE
Fix Reordering Queue

### ISSUE THREAD

**Issue by jmshrv** [jmshrv/finamp#212]
At some point, queue reordering broke, and the code for it looked a bit jank anyway. This should be fixed for 0.6.1.

**Comment by faizzzzz** [comment]
Were you able to figure out the root cause for this?
I noticed this only happens on when queue is shuffled. 
I noticed that the indices [here](https://github.com/UnicornsOnLSD/finamp/blob/master/lib/components/PlayerScreen/QueueList.dart#L62) are not the correct ones when shuffle is enabled. In comparison, [this](https://github.com/UnicornsOnLSD/finamp/blob/master/lib/components/PlayerScreen/QueueList.dart#L68) uses the correct index even when the queue is shuffled.

**Comment by jmshrv** [comment]
Fixed in #361
