### ISSUE TITLE
FlutterDownloader seems to ignore concurrency limits

### ISSUE THREAD

**Issue by ray-kast** [jmshrv/finamp#235]
I just recently installed Finamp on my phone (iOS 15.4.1) and went to go download a bunch of albums.  Maybe I'm misreading the download status indicator, but it appeared that FlutterDownloader consistently launched about 100 or so concurrent downloads at any given point in the process (rather than the configured `FDMaximumConcurrentTasks` value of 4) resulting in a ~50% download failure rate.  I suspect the likely solution to this issue is simply #213 as from what I can tell this is the fault of `flutter_downloader`, but I felt it was still worth reporting as a potential concern for download management.

**Comment by ray-kast** [comment]
![image](https://user-images.githubusercontent.com/6175424/168444470-2c4e29a0-5a3d-4767-ad39-95cef0c2e6b2.png)
Here's a relevant screenshot.  The number of failed downloads was originally 178 or so but I've since been chipping away at them by restarting the downloads on individual albums.

**Comment by UnicornsOnLSD** [comment]
Yeah this is tracked at https://github.com/fluttercommunity/flutter_downloader/issues/332 (there are probably duplicates too), but for Finamp I'll probably have the new download package done before that gets fixed. I think flutter_downloader is working on a 2.0, but it doesn't really fix what I need and development seems slow (or even abandoned if you look at the issues - I don't blame them though since some of those issues are especially low quality)

**Comment by jmshrv** [comment]
This personally isn't happening for me, I probably moved onto a patched version of `flutter_downloader` at some point
