### ISSUE TITLE
Remember last played track

### ISSUE THREAD

**Issue by Demian98** [jmshrv/finamp#240]
I'm using Finamp mostly for audiobooks and I really love it. My whole family is using and enjoying it in the meanwhile :)

The only downside is, that we need to remember on our own where we stopped listening. It would be great if Finamp could remember the last played track per album.

Simular to #60 are there any plans to implement this feature?

**Comment by dburanen** [comment]
I often hit the back button too many times too, closing the app, meaning I lose my last queue which is a bummer. If it remembered not only the last played track but the whole last queue, that would be better still.

**Comment by Chaphasilor** [comment]
@Mandeep56Singh this isn't GitLab so no fancy commands, do I understand correctly that you would like to take over this issue? 🤔

**Comment by Mandeep56Singh** [comment]
yes i would like to take this issue

**Comment by Chaphasilor** [comment]
There you go, have fun!

**Comment by Chaphasilor** [comment]
@Demian98 @dburanen the last played queue will now be stored when restarting the app, and you can also switch between previously saved queues. You can check it out here: https://github.com/jmshrv/finamp/releases/tag/0.9.2-beta

I'll close this issue for now since it should be resolved.

PS: we also have playback speed control in the pipeline, I'm guessing this will be of interest to you as well!
