### ISSUE TITLE
Support .lrc files + Equalizer

### ISSUE THREAD

**Issue by mxwmnn** [jmshrv/finamp#274]
Support synchronized lyrics with music and equalizer (10band if possible)

**Comment by UnicornsOnLSD** [comment]
I'd have to see if Jellyfin itself supports lyrics but it would be nice. Equaliser support would be dependant on https://github.com/ryanheise/just_audio/issues/147

**Comment by florinsdistortedvision** [comment]
Def lyrics support would be great, especially synced ones. Imo the only thing that's missing to make this app killer.

**Comment by mxwmnn** [comment]
[https://www.zerobin.tk/?129e8bd9d0d20944#EsMEmNbdE2UsuE5Wj5ymafdUXBsqKSxdiwYeftPy7t7y](url)

This is part of a ffmpeg transcode log. It's sending the existing .lrc file with it. So should be possible :)

**Comment by Chaphasilor** [comment]
> It's sending the existing .lrc file with it. So should be possible :) 

Are you sure the lyrics aren't already embedded in the file itself as a tag? What happens when you delete the `.lrc` file?

Also, even if it really loads the lyrics from the `.lrc` file, that seems to only be the case when transcoding, and not when direct playing.  
Otherwise, plugins like [Jellylyrics](https://www.reddit.com/r/jellyfin/comments/x7mltw/looking_for_betatesters_jellylyrics_adds_lrc_file/) wouldn't be needed.

The dev already said that they are looking into Lyrics support via this plugin, so it should be supported eventually.

**Comment by florinsdistortedvision** [comment]
Yeah those look embedded to the file. What I'm looking for is having:

Song.format (like song.mp3)
Song.lrc

Both in the same folder. Have it auto recognize and show the lyrics.

**Comment by mxwmnn** [comment]
My bad, sorry! It's really implemented in the file. I have done both, implement it and save it as .lrc

**Comment by Chaphasilor** [comment]
> Yeah those look embedded to the file. What I'm looking for is having:
> 
> Song.format (like song.mp3)
> Song.lrc
> 
> Both in the same folder. Have it auto recognize and show the lyrics. 

Yeah that completely depends on Jellyfin / server-side support.

**Comment by jmshrv** [comment]
This plugin could be used to implement this: https://reddit.com/r/jellyfin/comments/x7mltw/looking_for_betatesters_jellylyrics_adds_lrc_file/

**Comment by Y0ngg4n** [comment]
https://github.com/jmshrv/finamp/pull/334

**Comment by jmshrv** [comment]
EQ will be tracked at #453, closing this issue as #338 has had more discussion on lyrics
