### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by ChrisB85** [jmshrv/finamp#312]
I have just noticed that there are still some untranslated strings in app:

![finamp01](https://user-images.githubusercontent.com/792899/186758971-c7338a2d-2294-4993-b27e-4f0d57d62c78.png)
![finamp02](https://user-images.githubusercontent.com/792899/186758975-35b3aaaf-dd2b-4284-997e-651af6cf50b5.png)

I can't see "No items found" and "The list is currently empty." strings in Weblate.

**Comment by jmshrv** [comment]
The messages in the first screenshot are from the [infinite_scroll_pagination](https://pub.dev/packages/infinite_scroll_pagination) package, and there currently isn't a way to change them. There is a PR for it at https://github.com/EdsonBueno/infinite_scroll_pagination/pull/168, but that goes about it in a weird way and doesn't use the [intl](https://pub.dev/packages/intl) package like the rest of the Flutter ecosystem. I may stop using pagination in order to more cleanly implement #125.

As for the second screenshot, that has been fixed in 6fda25a :)
