### ISSUE TITLE
[Feature Request] Download entire library

### ISSUE THREAD

**Issue by DIWesser** [jmshrv/finamp#34]
Any chance you could create a way to 1) download an entire music library to the phone and 2) automatically update the local collection when there are new albums or the metadata is updated on the server?

I've been looking for a way to have a transcoded copy of my (mostly flac) library synced to my phone for a while now and this app seems like it could do it.

**Comment by UnicornsOnLSD** [comment]
I could create some kind of function to download the whole music library, but I haven't got transcoded music or syncing working next. I'm going to look into adding both, but I don't think Jellyfin has a way to download a whole transcoded song. I haven't looked into it that hard though, so there might be a way.

**Comment by DIWesser** [comment]
Oh, I should have looked more closely at the transcoding menu. I'd still be interested, but it sounds like a bigger ask than I thought.

**Comment by pewter77** [comment]
For sure interested in this! Transcoded downloads to mobile device would be great. Currently 120 songs in flac would fit on my phone... which is not so good.

**Comment by Chaphasilor** [comment]
@DIWesser @pewter77 the download system has been improved as part of the redesign beta. You can now download entire libraries at once, and even use transcoded downloads to save storage space. You can check it out here: https://github.com/jmshrv/finamp/releases/tag/0.9.2-beta

I'll close this issue for now since it should be resolved.
