### ISSUE TITLE
[Feature Request] Shuffle Artist

### ISSUE THREAD

**Issue by PutzJimmy** [jmshrv/finamp#35]
I have three libraries but only way i can find to switch between then it force stop the app and clear appdata and log back in.
Shuffle artist would be great too.

**Comment by UnicornsOnLSD** [comment]
I was going to add multiple libraries at some point so that I could add support for audiobooks (some people on Reddit wanted it). In the far off future, multiple libraries will be required for video playback too. May as well add it now :upside_down_face:.

I was thinking about adding the ability to play an artist's items too. I should be able to get it in with the next release.

**Comment by UnicornsOnLSD** [comment]
Library switching was added in 0.5.0, forgot to add artist shuffle but I should get that in soon.

**Comment by PutzJimmy** [comment]
Sweet! Love the great work 👌👌👌🤘

**Comment by UnicornsOnLSD** [comment]
Switching libraries has been added for 0.6, shuffle artist will likely come with the artist screen redesign. I probably won't get it done for 0.6 since it'll be quite a big change.

**Comment by UnicornsOnLSD** [comment]
Oh wait, I thought you meant like changing the selected libraries. Actually switching between libraries was added in 0.5 like I already said lol

**Comment by PutzJimmy** [comment]
Thank you so much for your awesome work on this. Really was the one bit that was stopping me from going from plex (plexamp) to full Jellyfin setup

**Comment by seniorm0ment** [comment]
Any updates on this?

**Comment by jmshrv** [comment]
Not currently, I believe the UI was discussed for the redesign though (although I could easily throw something together for now)

**Comment by Chaphasilor** [comment]
@PutzJimmy @seniorm0ment shuffling artists has been implemented as part of the redesign beta. There are options to simply shuffle all songs by an artist, and also to shuffle albums by an artist (so that the songs within an album are played in-order).  
You can check the beta out here: https://github.com/jmshrv/finamp/releases/tag/0.9.2-beta

I'll close this issue for now since it should be resolved.
