### ISSUE TITLE
Direct play is currently broken

### ISSUE THREAD

**Issue by Maxr1998** [jmshrv/finamp#414]
It seems that in 531625096ac23f2d2b67777f101d6c2f6a80cbdc, removing the container profiles broke direct play, which causes Jellyfin to transcode every streamed song to the default 128 kbit mp3 now. This also breaks seeking because the client doesn't use HLS in this case.

**Comment by jmshrv** [comment]
Oh god oops, I hadn't noticed that. I'll do some more testing soon, my server is currently down (fan started making a horrible grinding sound).

**Comment by Maxr1998** [comment]
Ouch, I hope you can get your server up and running again soon!

**Comment by jmshrv** [comment]
I think it breaks HLS too lol

**Comment by jmshrv** [comment]
Reverted https://github.com/jmshrv/finamp/commit/531625096ac23f2d2b67777f101d6c2f6a80cbdc, will fix the issue that it fixed later. I'm thinking of making direct play just use the `/Items/{itemId}/File` endpoint so that Jellyfin never tries to transcode it. Hopefully Jellyfin can clean up the audio (and presumably video) APIs at some point, it's really awkward trying to get it to do what you want. While debugging this I've noticed that it'll use a cached transcode even if the bitrate is different, not sure if that's a bug in Jellyfin or Finamp

**Comment by jmshrv** [comment]
Started using `/Items/{itemId}/File` in b03c119. I'll have a look through universal audio's code on Jellyfin's side to make sure it isn't doing anything important, but this should work for the long term since it'll never transcode on that endpoint
