### ISSUE TITLE
Unable to log out 

### ISSUE THREAD

**Issue by ttobmister** [jmshrv/finamp#423]
After the address of the JellyFinn server changed or went from http to https, the app can no longer connect preventing me from logging out to change the server address.

**Comment by jmshrv** [comment]
If you log out in airplane mode you should be able to get through, I really need to add a timeout to that request

**Comment by ttobmister** [comment]
yeah so when my phone went completly offline it had a little freak out showing a light grey screen on the albums page, said connection timed out and booted me to the login screen. why not just allow logging out in offline mode?

**Comment by jmshrv** [comment]
Looking at the code, what likely happened is the logout command finished (presumably when you disabled internet), but you were briefly on the music screen so it got very confused since there wasn't a user. It would be useful if you could manage to reproduce that and send logs, but I wouldn't worry about it too much. I've added a timeout in aee1efc, so this in theory shouldn't be an issue.

I could also [make Navigator use a global key](https://stackoverflow.com/questions/52962112/how-to-navigate-without-context-in-flutter-app#53397266), as navigating to the log in screen depends on the log out button still being in the widget tree to do the actual logout, as can be seen here:

https://github.com/jmshrv/finamp/blob/aee1efc088ef182dcfd03081074dbd5ccc9a7a44/lib/components/SettingsScreen/logout_list_tile.dart#L75-L78
