### ISSUE TITLE
[Security issue] Remove or hide credentials on the logs

### ISSUE THREAD

**Issue by magicDGS** [jmshrv/finamp#454]
I realized that the logs contain the credentials in clear text once you log in. This is a security risk that should be fixed, or otherwise it might allow credentials to be shown when sending logs or even if another malicious app scans the log data. Also, please provide a way to remove the log data and/or be less verbose for the final user.

**Comment by jmshrv** [comment]
Thanks for the concern, this is not an issue as logs are sanitised when shared. The following items are removed when sanitised:

* Username/password for initial authentication request
* Base URL
* Access token

The function for this is:

https://github.com/jmshrv/finamp/blob/5ed5fc9d866cbc3a929e765d66889e54500bedb1/lib/services/finamp_logs_helper.dart#L35-L51

Logs are not written to storage, and just exist as an array. A malicious app would need to somehow get access to Finamp's memory, in which case something has gone terribly wrong on the user's phone.

I want to keep logs visible as it allows users to provide better bug reports. Otherwise, I'd have to collect logs using something like Sentry, which then means that I have to get involved in data collection.

**Comment by magicDGS** [comment]
I see, then it's secure from the malicious apps side, but this is not what I saw from the UI (installed form play store). Having my phone/tablet with that credentials on the UI when I am out of home is also a potential risk if someone see it. Could be also hidden there?

**Comment by jmshrv** [comment]
When collapsed, log tiles will now censor the username/password. There is also a confirmation dialog to prevent accidentally showing credentials.

<img width="395" alt="Screenshot of censored log tile" src="https://github.com/jmshrv/finamp/assets/44349936/da215a61-0925-4376-b918-1cf6304f0e8b">

**Comment by magicDGS** [comment]
Thanks a lot. Looks like the perfect solution.
