### ISSUE TITLE
[Feature Request]  Implement Artist view in Offline Mode

### ISSUE THREAD

**Issue by enduring78** [jmshrv/finamp#462]
Currently, when in Offline Mode, I can't search or view the artists tab because it isn't implemented. 

I have searched the issue tracker but couldn't find a issue asking for this, so I made one!

**Comment by NoSadBeHappy** [comment]
Yeah I was wondering what the reason is that it hasn't been implemented yet? What issue have you run into when making it? I would be happy to help.

**Comment by jmshrv** [comment]
I'll give a technical description here to be thorough. **TL;DR: Finamp can't model relationships beyond album/playlist -> song right now**

Here's a little diagram that I wrote up in 5 minutes:

![Drawing comparing Finamp's current download system vs ideas for a new one. Text explanation below.](https://github.com/jmshrv/finamp/assets/44349936/ff529c94-1efd-4a39-9510-63c0542047a9)

Finamp currently models downloads with `DownloadedParent` and `DownloadedSong`. This is a very simple relationship - parents contain songs. This works for albums and playlists, but isn't suitable for artists (or genres and other higher-level categories). **It's a single-level relationship.**

The new system will allow `DownloadedParent` objects to depend on other `DownloadedParent` objects. This'll make downloads look much more like a graph, and will allow us to add third-level collections like artists and genres. This solution will make migrating from the old system relatively easy, which would avoid the pretty bad proposition in [the downloads plan](https://github.com/jmshrv/finamp/blob/main/DOWNLOADS_PLAN.md) where downloads will disappear on upgrade.

The new system is still in the theoretical stage (I'd like to get #220 sorted first)

I haven't mentioned how images are implemented, partly because it isn't relevant here, partly because I've forgotten exactly how they're implemented and they're kind of stapled on (which further makes me want to rip out the current download system).

**Comment by jmshrv** [comment]
(the drawing is 6809x11992, apologies if your computer exploded loading it)

**Comment by Chaphasilor** [comment]
> a little diagram that I wrote up in 5 minutes

https://media.tenor.com/aAsftu-ZFLUAAAAC/ron-swanson-parks-and-rec.gif

Also, I'm not sure if the redesign is independent of this. An improved artists screen (all albums, all songs, etc.) might require some rework anyway? Unless the offline stuff is fully independent...

**Comment by NoSadBeHappy** [comment]
Wow thanks for the description! So basically right now finamp literally doesen't know what artist the song is by when you download it. That makes sense. I don't know how to implement it, but isn't there a way to get metadata from jellyfin? Could finamp just save that, and then use that to sort?

**Comment by jmshrv** [comment]
We get the name of the artist, but not enough to easily "recreate" the artist screen.

When getting artists in online mode, Finamp calls the `/Artists/AlbumArtists` endpoint to get the list of artists. From there, we can request a specific artist using the same call as albums/playlists. This call includes much more info, which is required to actually display the artist (especially when Finamp starts showing artist metadata instead of just a list of albums).

**Comment by NoSadBeHappy** [comment]
Ah, okay thank you for the clarification.

**Comment by ldexterldesign** [comment]
👋

Thanks for software! 😍

*So* looking forward to playing (my own FLAC) offline music on my smartphone again since switching to iOS

To clarify - and for the benefit of others who may come here - is this issue the reason/bottleneck to playing offline music or is there something I'm missing..? 😕

Yours hopefully

**Comment by ldexterldesign** [comment]
> To clarify - and for the benefit of others who may come here - is this issue the reason/bottleneck to playing music offline or is there something I'm missing..? 😕

Ahh, I seem to have got things working - playing is possible just not via certain views 👌

Feel free to delete my comments

Apologies for noise 😔🧥

👋

**Comment by Chaphasilor** [comment]
@enduring78 @NoSadBeHappy the download system has been improved as part of the redesign beta. Artist support for offline mode is now available, and we have an improved artists screen that also shows top songs. You can check it out here: https://github.com/jmshrv/finamp/releases/tag/0.9.2-beta

I'll close this issue for now since it should be resolved.
