### ISSUE TITLE
Songs Tab Clicking Only Plays One Song Instead of Creating Queue

### ISSUE THREAD

**Issue by Garret-Martin** [jmshrv/finamp#473]
Under the songs tab, clicking a song does not create a queue, it only plays one song. It would be nice if it was similar to how the albums work, where clicking a song will queue the rest chronologically. The songs tab on the regular jellyfin app generally works the way I like as far as running through the songs list the way I filtered or sorted it, so it would be nice if that was brought to finamp (I understand if this was a choice).

**Comment by Chaphasilor** [comment]
This is somehing that I'll definitely add as part of #220. However, just queuing all songs in order is quite challenging, because there are libraries with tens of thousands of songs. Pressing Shuffle All currently only queues 250 songs by default, and that's for a reason.  
Maybe we can figure out a way to dynamically queue more songs just-in-time, but for now the simplest solution would be to start an Instant Mix from this song.  
Would this solve your problem? :)

**Comment by Garret-Martin** [comment]
This sounds great. Thanks for explaining the problem. I doubt I'd every listen to 250+ songs at one time so whatever solution would be easiest to implement will work just fine. 

A lot of the work in #220 looks really great and promising, and will greatly improve the experience.

**Comment by Chaphasilor** [comment]
I'll close this since the PR has been merged now and the beta should arrive soon. Also, there's discussion about improving the feature (or having more options) in #502
