### ISSUE TITLE
Feature Request: Creating a website for "Finamp"

### ISSUE THREAD

**Issue by yaten2302** [jmshrv/finamp#503]
Hi @jmshrv, this is a feature request for creating a website dedicated to "Finmap" and letting the users know about this app easily.

**Comment by jmshrv** [comment]
That'd be a pretty good idea, I really need to clean up Finamp's presentation. It got the job done early on, but it's grown a lot since then.

**Comment by yaten2302** [comment]
Should I start working on this issue, if a website is required?

**Comment by Chaphasilor** [comment]
Given that this is not directly related to the app itself, maybe this should be converted to a discussion :)

I agree that a nice website would be pretty neat, and the GitHub readme could also use some work. Once the beta is out we could tackle the readme.  
Are there any guidelines regarding the content shown? I noticed many music players blur covers in the screenshots or use very generic demo media. Is this due to copyright reasons?

@yaten2302 if you want to start working on an app I could provide you with screenshots/designs and the likes. Depending on how elaborate the website should be I could also assist with the design, although currently I'm more focused on redesign of the actual app

**Comment by jmshrv** [comment]
To be fair we could just fix up the README and use GitHub pages (or some very basic Markdown to HTML).

> Are there any guidelines regarding the content shown? I noticed many music players blur covers in the screenshots or use very generic demo media. Is this due to copyright reasons?

Yes, especially on app stores. Finamp got rejected until I proved that the demo server music was royalty free.

**Comment by Chaphasilor** [comment]
@yaten2302 if you want to have a go at this then just go ahead! The redesign is well underway, but there is no need to wait until it is finished :)

**Comment by yaten2302** [comment]
Yes, sure @Chaphasilor, I'll start working on it 👍. Should I send a prototype of the website here first?

**Comment by Chaphasilor** [comment]
Would probably be best if you set up a public repository and share the link 🤔  
Which language/framework are you planning to use for the app? :)

**Comment by yaten2302** [comment]
Yeah sure, will make a public repo 👍
I'm planning to use HTML, CSS and JavaScript. I know Tailwind CSS also.

**Comment by yaten2302** [comment]
Hi @Chaphasilor, actually I've a doubt, I've started working on the website, but will my contribution be counted in hacktoberfest? Because for hacktoberfest, a PR has to be made.

**Comment by Chaphasilor** [comment]
That should be possible. At the end you could make a PR that adds a link to the website to the readme or something? 🤔

**Comment by yaten2302** [comment]
> That should be possible. At the end you could make a PR that adds a link to the website to the readme or something? 🤔

Ok, sure, will do that 👍

**Comment by yaten2302** [comment]
Hi @Chaphasilor, could you please send some screenshots of the app, some FAQs and also an about section, so that those can be put in the website.

**Comment by Chaphasilor** [comment]
### About

Finamp is a Jellyfin music player for Android and iOS. Its meant to give you a similar listening experience as traditional streaming services such as Spotify and Apple Music, but for the music that you already own. It's free, open-source software, just like Jellyfin itself.  
Some of its features include:
- A welcoming user interface that looks modern & unique, but still familiar
- Downloading files for offline listening
- Transcoded streaming for saving mobile data
- Beautiful dynamic colors that adapt to your media
- Full support for Jellyfin's "Playback Reporting" feature and plugin, letting you keep track of your listening activity

### Frequently Asked Questions

(@yaten2302 can we split this up into two sections?)

#### Before Installing

##### Is Finamp free?
Absolutely! It costs nothing to use. We do appreciate voluntary contributions of any kind though, be that bug reports, code, designs, or ideas for new features. You can also donate to some of the developers to show your appreciation <3

##### How can I install Finamp?
On Android, Finamp can be installed from the Google Play Store, F-Droid store, or directly by installing the APK file from GitHub.  
On iOS, you can install Finamp through Apple's App Store.

##### Does Finamp support my media formats?
Finamp should support all formats supported by Jellyfin. Some more advanced formats could cause issues for regular playback, but transcoding should fix these issues.

##### Does Finamp support Android Auto / Apple CarPlay?
Theoretically, but not yet. There is [an issue for this](https://github.com/jmshrv/finamp/issues/24) that contains a proof of concept for Android Auto in there, but it hasn't been tested yet. Maybe you could help out!

##### Is Finamp legal?
Yes. Finamp is a *tool* that lets you interface with a Jellyfin server. Finamp does not come with any music, and will not connect to streaming services other than Jellyfin. You will need to bring your own media and add it to Jellyfin, for example by purchasing music online. This often also directly supports your favorite artists!

#### After Installing

##### I'm having trouble with Finamp, where can I find help?
If you're experiencing software bugs or other issues with Finamp, be sure to take a look at [Finamp's issue tracker](https://github.com/jmshrv/finamp/issues), especially the pinned issues at the top of the page. If you can't find anything related to your specific problem, please create a new issue (you will need a GitHub account).

##### My Playlists aren't showing up!
A recent Jellyfin update (10.8.11) included some changes to how playlists show up. This was done by mistake and should be fixed in a coming Jellyfin update soon. In case the update is delayed, we will try to temporarily change how Finamp shows playlists until the problem is resolved.

As for screenshots, just use placeholders for now (like the ones from the readme)

**Comment by Chaphasilor** [comment]
Hey @yaten2302 any progress with this? :)

**Comment by yaten2302** [comment]
Hi @jmshrv, currently the work is in progress, I was not able to complete it due to some issues, I'll create the PR ASAP.
