### ISSUE TITLE
Shuffle on Artist does not queue correct

### ISSUE THREAD

**Issue by Y0ngg4n** [jmshrv/finamp#514]
If you shuffle on an artist it plays the first song and then the last in the queue and then stops.

**Comment by Chaphasilor** [comment]
I'm not able to reproduce this. Which version are you using, and can you give a more detailed repro? 🤔

**Comment by Y0ngg4n** [comment]
@Chaphasilor Versions 0.6.18

**Comment by Chaphasilor** [comment]
@oscarale-camorlinga thanks for the repro. Interesting, that shouldn't be happening anymore. I wasn't aware the issue is also happening with albums and playlists.

I already created a PR for the artists shuffling (#515), but I will go ahead and update that to also fix the issue for albums and playlists (tomorrow)!

**Comment by Y0ngg4n** [comment]
Thank you @Chaphasilor
