### ISSUE TITLE
ability to add genres to your mix

### ISSUE THREAD

**Issue by Behem07h** [jmshrv/finamp#548]
long pressing a genre should give an option to add it to your mix. this way we can make mixes consisting of songs from multiple (specific) genres easily

Creating an instant mix from the songs tab is inflexible as it overrides the current mix rather than adding to it, and it makes choosing a genre unnecessarily difficult as songs dont display which genres they are from.

**Comment by Chaphasilor** [comment]
This will be possible with the next **beta** update. It will work like the mix feature for artists and albums, where it doesn't actually create an instant mix, but instead shuffles all tracks from the selected genres. There is not way to get an instant mix for *multiple* genres from the Jellyfin server, that's why need to do it this way.  
Should works just fine for your use case though!

**Comment by Chaphasilor** [comment]
@Behem07h this has now been released with the latest beta update (0.9.5)
