### ISSUE TITLE
[Feature Request] Android: themed icon support

### ISSUE THREAD

**Issue by foss-** [jmshrv/finamp#583]
Would be nice to add support for themed icons:
https://developer.android.com/develop/ui/views/launch/icon_design_adaptive

**Comment by againstpetra** [comment]
this has been included in the redesign: https://github.com/jmshrv/finamp/issues/525#issuecomment-1792375094

though - it would be nice if it were backported to the current main branch and released separately, given the resdesign is still not in beta and will take a while to land in stable. not sure if that's possible.

**Comment by foss-** [comment]
Searched for `themed` and thus didn't find the existing issue. Closing as duplicate of https://github.com/jmshrv/finamp/issues/525

**Comment by Chaphasilor** [comment]
> it would be nice if it were backported to the current main branch and released separately, given the resdesign is still not in beta and will take a while to land in stable. not sure if that's possible.

The problem there is that adaptive icons require a minSdkVersion of 26, up from 21. That means Finamp will only work on Android 8.0 and above, when it previously worked on Android 5.0 and above.  
For the redesign this shouldn't be a huge issue, because it's a breaking change anyway, but I'm sure there are some people running Finamp on older versions of Android that would like to keep getting the stable channel updates, for a little while longer at least. Therefore I don't think this will be backported :)
