### ISSUE TITLE
[Redesign] Adding songs to playlists is cumbersome

### ISSUE THREAD

**Issue by snppls** [jmshrv/finamp#629]
I think adding songs to playlists could be streamlined. In the example I provide below it takes 5 clicks to add a single song to a playlist. This is not so much fun when trying to quickly put together playlists.

![Playlist](https://github.com/jmshrv/finamp/assets/156883144/7dd9b810-a7b4-48a1-9e52-565d6f946e2c)

I think the sleep timer currently is given too much design priority. It is a useful but rarely used function - I personally don't use it, but I would imagine those that do, use it once a day at most? Could the playlist button be added in its place like in the mockup below?  Perhaps the sleep timer could be moved to the queue screen instead, or somewhere else a little more hidden?

![suggestion](https://github.com/jmshrv/finamp/assets/156883144/06c0ee5a-eb8e-4033-af90-68f66dc31db8)

**Comment by snppls** [comment]
Another option would be to change the priority of the options in the last image. 

I would think "Remove Favourite" would be a little used feature. This repeats the functionality of what can already be achieved on the player screen anyway by click the heart shape again.

Perhaps "Add to playlist" could sit above "Add to Next Up" and "Remove Favourite" could sit further down the list?

**Comment by Chaphasilor** [comment]
The new order in the menu will be:
1. Add to Playlist
2. Add Favorite (because there's no other way to favorite for the regular menu (not on the player screen)
   - I'm planning to add a simple heart icon to the top right corner of the top section of the menu at some point, then we can move the option further down.
3. Add to Next Up, etc.
4. Remove from Playlist

Does that work for you?

**Comment by bsfreq** [comment]
I agree with the OP. Just came here to suggest that "add to playlist"- button should be directly available on the player page. (for example below or above the like-button) Actually, wasn't it there on an earlier, non beta version of Finamp?
I use (and add songs to) playlists a lot, and having to tap the hamburger menu, scrolling down, and then tapping add to playlist is just way too cumbersome. 

I just joined the discord channel, and there was someone requesting a more clean ”currently playing” view. I pose an opposing view, as I like good usability more than a simple, sterile and clean view. You can quickly learn the location of needed info and buttons on a single page. And there’s still room to add more functionality. However, I do understand the opposing view as well. If someone just wants a simple player, then perhaps there could be a settings option to hide / show some functions on the player page. In fact, I would love to see even the currently playing media info there too (audio format, bitrate etc.). 

Thank you for your work!

**Comment by snppls** [comment]
Yes, thanks for that. That will streamline adding songs to the playlist quite a bit.

**Comment by e-v-o-l-v-e** [comment]
I have no idea how it would be possible to do this but spotify new playlist system is really awesome and a similar implemention of it would solve this problem wich i also have, as I do like to have a_lot_ of playlist, here you go :

![spo1](https://github.com/jmshrv/finamp/assets/84813895/0d0bc69d-6eaf-42ab-91df-9c5f9ce11681)
![spo2](https://github.com/jmshrv/finamp/assets/84813895/8b0a64be-f03f-40dd-a6e5-8ba974923211)
![spo3](https://github.com/jmshrv/finamp/assets/84813895/3746f2bb-172a-45ec-a46d-e407a0c1a39e)

in the first screenshot the song is not in any playlist, when you click the + button it gets added to liked song, 
giving the second screenshot, and if you click it again you get a list to check (third screenshot) (or uncheck,finally, after all this time someone made this) all the playlist you want to add the song to, as you can see spotify also support folders. which would also be great in a second time

**Comment by Chaphasilor** [comment]
In Finamp/Jellyfin, there's no "Liked Songs" playlist like Spotify now has, so what would the default playlist be? Favoriting a song and adding it to a playlist are two separate things in Jellyfin-land 🤔  
The semantics are also a bit different. Spotify has over 100 million tracks, so it makes little sense to have a "shuffle all" functionality. But on your Jellyfin server, you probably only have music that you like anyway, which would be similar to what the "Liked Songs" playlist in Spotify does.

Theoretically Finamp could emulate this behavior, by having a virtual "Favorites" playlist that contains all songs that are liked, and adding a song to that playlist marks it as favorite. That would get you pretty close to Spotify's behavior.  

The details are still a bit hazy though. Do we keep the heart icon, so people can easily find the way to favorite a track? Do we keep the "Add to playlist" functionality? Should this be an option, or the only way to do it?

I think such a change would require some user research first, to make sure that the behavior matches people's goals and expectations. But I'd be happy to take a look at a proof of concept, if someone feels like implementing that. It actually shouldn't be too complicated, the hardest part is the virtual playlist (but I'd consider this optional for now).

**Comment by Chaphasilor** [comment]
We're making good progress for this request! The next update will change the liking + adding to playlist interactions quite a bit, with a new menu similar to Spotify's being the default when tapping the like button. There you can add the track to favorites, remove it from the current playlist (if one is playing), and directly add it to any other playlist.  
The heart icon of the like button will still only reflect the favorite status of the track, because showing if a track is part of any playlist is a) not possible at the moment due to missing server support, and b) not really suited for Jellyfin, since all tracks are already inside your library, so there's little benefit.

You can also still directly like or unlike a track, either by long-pressing the like button, or by double-tapping the album cover.

One limitation for now is that we cannot tell which playlists a track is already part of (except for the currently playing playlist), that might be possible with Jellyfin 10.10.

This should then hopefully address all of your requests. @snppls the number of required interactions to add the currently playing track to a playlist will be reduced to 2, @bsfreq there is now a button that directly allows you to add the track to one or multiple playlists, @e-v-o-l-v-e you'll get as close to the Spotify experience as currently possible.  
Let me know what you think!

**Comment by e-v-o-l-v-e** [comment]
wow, this is amazing, thank you !

**Comment by Chaphasilor** [comment]
Closing since I consider this to be fixed :)
