### ISSUE TITLE
[Redesign][Feature Request] In player screen, show remaining song time instead of duration

### ISSUE THREAD

**Issue by Ivanf1** [jmshrv/finamp#664]
Hello! Coming from the Music app on iOS, in the player screen, I'm used to see the remaining time of the song currently being played instead of the duration.

What I would like to propose is to add a toggle in the settings that would allow to choose between the current behavior (show the total duration) or show the remaining time.

If this is something that you think could be worth to add, I could start working on it.

**Comment by Chaphasilor** [comment]
Hey! Yeah that sounds absolutely doable, and very straight-forward to implement! Just subtract the current position from the total duration at the right spot in the control area, and add the setting. Let me know if you want to handle it yourself, otherwise I can do it to!

Do you think the "time remaining" behavior should be the default on iOS, or should the default stay the same? Do other music apps like Spotify or Youtube Music also show the remaining time on iOS, or just the default music app?

**Comment by Chaphasilor** [comment]
Interesting that the behavior really is different between the platforms. You can test out Youtube Music's behavior without a subscription, it just won't allow background playback and will have ads afaik.

But yes, setting the default value of the setting to `true` for iOS sounds like a good idea then.  
And the rounding is also the best approach I think, since the values are rounded down to seconds anyway. Maybe make sure the values actually are rounded and not just truncated, to prevent glitches in edge cases :)

Oh and don't forget to add the minus/hypthen as a prefix in that case, like the other apps do!

**Comment by Ivanf1** [comment]
The default behavior on YouTube Music is to show the total duration and it does not seem to have an option to change it to the remaining time.

**Comment by Chaphasilor** [comment]
Okay, yeah that doesn't really surprise me. We can proceed as planned though 👌🏻

**Comment by Chaphasilor** [comment]
@Ivanf1 are you still planning on making a PR for this?

**Comment by Ivanf1** [comment]
Hi! Unfortunately I don't have enough time to work on this issue anymore.

**Comment by Chaphasilor** [comment]
@Ivanf1 this is now part of the beta! There's still a bug with track longer than one hour, but that will also be fixed with the next update :)
