### ISSUE TITLE
[Redesign] Previous track button does not play previously listened track

### ISSUE THREAD

**Issue by snppls** [jmshrv/finamp#679]
Would it be possible to have the previous track button use the playback history as its reference?

If I press the previous track button after switching to a new album it goes to the previous track of _that_ new album rather than the previous song I was listening to. Even worse - if it is first track within that new album, it will just return and replay the same current song.

I think most users would expect the previous button to play the track they were _previously_ listening to rather than the track that precedes it in that specific album.

**Comment by Chaphasilor** [comment]
Hmm, I'm not sure. Finamp operates on a queue, and that queue is updated when you start playback of a collection (i.e. an album or playlist).  

While it would probably be possible to do what you're suggesting, it would most likely cause a few issues with the actual audio player we're using.

What I would suggest instead is that you use something like "Add to Next Up" instead of "Play" to add the album to the queue, that would give you the behavior you're looking for. You'd only have to skip to the next track after adding to the queue.  
I can also imagine adding an option to make "Add to Next Up" the default play action, possibly followed by an automatic skip. That would be beneficial in other cases too, like Android Auto voice commands.

To have "Skip back" wrap-around to the last track of the album, you just need to enable "Loop All" mode.

What do you think?

**Comment by snppls** [comment]
Thank you for the detailed explanation. I will try your suggestions. 

I think changing the play action to "Add to Next Up" along with an automatic skip is a clever way to get the same functionality.  Provided there are no significant downsides I think this would add quite a bit of functionality as many users tend to skip around to different artists, albums, and songs these days rather than listening to a single album from beginning to end. 

I don't have a strong opinion either way on a "skip back wrap around" option.

**Comment by Chaphasilor** [comment]
Adding an option to make "add to Next Up" the default playback option, and/or making it so after adding something to Next Up Finamp immediately skips to that track are things that I've considered myself already, but I think that's a different issue.  
I probably wouldn't want that behavior all the time, and haven't figured out how to support that scenario.

But changing how the queue works is not something that I'm planning to do, sorry...
