### ISSUE TITLE
0.9.3+ beta package appears invalid - Pixel 6 android 14.

### ISSUE THREAD

**Issue by amnnku** [jmshrv/finamp#711]
Hi there

Love the improvement in beta 0.9.2 on android, but have been unable to update the app with any betas since that version.

They all give me the same error above. 0.9.2 works great.

Have the supported versions of android been updated or something, as I have downloaded multiple times with the same error message.

Thanks.

**Comment by Chaphasilor** [comment]
Hi, this is probably because you used one of the platform-specific APK from the 0.9.2 release, which we don't include in releases anymore. Sadly it's not possible to update using an universal APK after using a platform-specific APK for the initial installation, so you'll have to uninstall the old version and install the latest version instead.

Take notes of your settings and downloads so you can easily get back to the previous state!

Sorry for the annoyance...

**Comment by amnnku** [comment]
> Hi, this is probably because you used one of the platform-specific APK from the 0.9.2 release, which we don't include in releases anymore. Sadly it's not possible to update using an universal APK after using a platform-specific APK for the initial installation, so you'll have to uninstall the old version and install the latest version instead.
> 
> Take notes of your settings and downloads so you can easily get back to the previous state!
> 
> Sorry for the annoyance...

Cool, thanks, that worked :)

**Comment by Chaphasilor** [comment]
Awesome! Let me know if you run into any other issues! :D
