### ISSUE TITLE
Songs skipping while playing.

### ISSUE THREAD

**Issue by TreeTrunk221** [jmshrv/finamp#716]
While playing certain songs, the songs will end abruptly and skip to another song, but only when playing in a playlist after the first song has played, and some songs don't skip and say they are at the end but actually aren't.

**Comment by Chaphasilor** [comment]
Is this on iOS? What phone and Finamp version are you using?

**Comment by rodofiron** [comment]
I have the same issue with the newest beta (0.9.7) on a Samsung Galaxy A10e running Android 11. It seems to happen randomly when utilizing the shuffle all songs button. Some songs will play to completion and others will stop at random intervals and immediately start the next shuffled song.

I did not have this issue with the last stable release so I've gone back to using that for now.

Thank you for the amazing work! :)

**Comment by Chaphasilor** [comment]
@rodofiron it really sounds like there would be something wrong with your media, but if that were the case it probably wouldn't work in the stable version.  
Are you sure that you don't have transcoding enabled in the stable version?

**Comment by rodofiron** [comment]
Everything is directly played. I've been using Finamp for a long time to play a small library of songs (flac) without this issue.

**Comment by rodofiron** [comment]
I reinstalled the beta to do more testing since I think I forgot to disable the battery saver and the same issue persists w/ the battery saver off, in addition to the app crashing randomly while I was using it. I wanted to check the logs but it crashed while I was looking. At one point my phone gave me a message asking what to do since it keeps crashing.

Sometimes playback would just stop, and sometimes as I said the next song in the queue would start up before the current song was done playing. I'm currently playing the same songs with the stable version and am having no problems. My server version is 10.8.13 as I haven't upgraded to the newest version yet.

I've also used Symfonium in the past which had major issues with my (old) phone's aggressive battery management and poor specs in general. All I can guess is that this also might be the issue here if I'm the only one with these specific problems.

**Comment by Chaphasilor** [comment]
Hmm, it's not like the 10e is ancient or under-powered. Would be nice if you could try to somehow grab logs!

What codec does your media use? Could you try if it works when transcoding? Which version is you Jellyfin server?

As for increasing performance, here are some setting you can apply. Important are the buffer duration and blurred backgrounds. Enabling transcoding with a low bitrate might also help.

![Screenshot_20240526-163629.png](https://github.com/jmshrv/finamp/assets/18015147/fd31c445-cc01-4e85-9c44-c307eeef9eb6)

![Screenshot_20240526-163817.png](https://github.com/jmshrv/finamp/assets/18015147/0e6494b6-f8d4-48bb-879b-b06f953d9ec2)

**Comment by rodofiron** [comment]
Thank you for taking the time to show me how to improve performance!

My media are all FLAC files (around 100mb each) and I'm running server v10.8.13 on Linux Mint 21.3 Cinnamon.

I turned on transcoding (192 kbps) and made your noted changes. In the Jellyfin dashboard on my pc it still reports the file as being directly played (even after a Finamp restart). I can't figure out why. But, changing the options you suggested appears to have solved the issue, transcoding or no transcoding. No crashes, skips or stoppages any more with transcoding on or off.

I'll definitely grab logs if things are stable enough to do so should this happen again. I'll also try and investigate the transcoding discrepancy because I don't recall ever having an issue w/ the stable.

Thanks again for your help :)

**Comment by Chaphasilor** [comment]
Yeah we haven't yet figured out how to make the Jellyfin dashboard show the transcoding status, it's on my TODO list. If Finamp says that the track is transcoding on the player screen, it really is transcoding! If you want to confirm that, you can check the ffmpeg logs in the "Logs" section in Jellyfin, there should be a recent one (not necessarily the latest one, since we're pre-fetching) that corresponds to the playing track.

I think I know what the issue might be. The beta's default value for buffering is 600 seconds, or 10 minutes. That means Finamp will load the audio for any upcoming tracks, until the end of the queue is reached or the total loaded duration is around 10 minutes. Doing that for high-quality FLAC will eat up a significant amount of RAM/memory. We should probably reduce the default buffer duration a bit to avoid this.  

If you're happy to listen to transcoded audio (even the maximum transcode bitrate should be much smaller than your FLACs), you can probably just enable transcoding and increase the buffer duration again. If you want to direct play your FLACs, you could test out how many seconds you can buffer before issues start appearing.  
When changing the buffer duration, you may have to restart the app for the change to be applied :)

**Comment by rodofiron** [comment]
Got it! FYI you are correct about the transcoding (indicated by logs). But like I said I haven't had any issues w either transcoding or direct play since changing the settings (including the buffer duration). I wonder if this would solve op's issue as well.

Thanks again for helping me and I wish you luck with all your projects :)

**Comment by Chaphasilor** [comment]
@TreeTrunk221 since you're not responding and we found a potential cause, I'll close this issue for now. Feel free to re-open if you have more details to share!
