### ISSUE TITLE
[Beta issue] Android downloads show up in app cache and do not count towards app size

### ISSUE THREAD

**Issue by nathan-contino** [jmshrv/finamp#718]
Not a particularly hazardous bug, but solidly in the "midly irritating" camp.

Expected behaviour: in the "Apps" section of "Storage", Finamp shows the total space consumed by downloads.
Actual behaviour: in the "Apps" section of "Storage", Finamp shows the space consumed by the APK. Much less than the space consumed by downloads.

Noticed this issue when I switched to the beta. Previously, downloads counted as "user data" and went towards the total space consumption of my phone. In the beta download system, downloads show up in cache (which presumably means clicking "clear cache" will delete all of them? or that the system could clear them automagically if it needs extra space?), and it seems like cache usage doesn't count toward total device storage usage (notice that my total app space usage is less than the size of my finamp cache). Which is arguably an Android bug, but worth noting. Even weirder since Android acknowledges the cache in "total space". 

Tested on a Google Pixel 4a running Android 13. Given the state of modern Android, it wouldn't surprise me if Android 14 or 15 solves this issue, in which case you can safely ignore it.

![Screenshot_20240504-080355](https://github.com/jmshrv/finamp/assets/10657588/e1260404-97d2-437e-b344-63dfae06f798)
![Screenshot_20240504-080342](https://github.com/jmshrv/finamp/assets/10657588/f9b1e8af-a503-4eac-b0fb-49f37b837642)
![Screenshot_20240506-094109](https://github.com/jmshrv/finamp/assets/10657588/8cc1edfa-5787-42bc-9868-b0700ace4b23)

**Comment by nathan-contino** [comment]
Grrr, just confirmed that this is indeed an Android bug. Sometimes the App menu shows the true size of the app, but close and reopen Settings and it'll forget again.

![Screenshot_20240506-094614](https://github.com/jmshrv/finamp/assets/10657588/6d73aa9a-7017-4f2c-a669-fa3c12d70d9e)


Closing because this is a Dumb Android Thing and y'all are doing things just fine.

**Comment by Chaphasilor** [comment]
It probably takes a bit to calculate the size. It's just scanning the app directory and adding up all file sizes in the background :)

**Comment by Maxr1998** [comment]
I actually think this is a bug in the beta. Because I noticed that all files downloaded with the new downloader suddenly count towards the cache for me too, and not the app data.
On my new phone, which only used the beta, everything is counted as cache (over 30 GB).
The library location I used is in `/storage/emulated/0/Android/data/com.unicornsonlsd.finamp/files` in both cases, which shouldn't be counted as cache usually.
Interestingly, I noticed that on my old phone, songs in the `songs` subfolder have user u0_aXXX, but group `u0_aXXX_cache`. I didn't even know that was a mechanism on Android and also couldn't find any documentation on it while doing a quick search.
Changing the group to `ext_data_rw` like for the other files fixes this issue and causes the system to properly report cache size again.
