### ISSUE TITLE
Volume Normalization's Base Gain feature on iOS does not have a limit nor the option to input negative sign

### ISSUE THREAD

**Issue by RantoPhantom** [jmshrv/finamp#727]
### Device/OS:
- iPhone 12 running iOS 17.5, and app is on the latest Finamp version on TestFlight

### Problem:
- The Base Gain adjustment input does not have any option to input the negative sign hence why I can input positive number, see the attached image below

<img src="https://github.com/jmshrv/finamp/assets/64245707/ae3f65d7-f83f-4c87-ae50-5f1d3f89a8be" width=25% height=25%>

- This is a problem because it will use the positive number to boost the gain instead of decreasing it. (it will still increase the volume even if the volume slider is maxed out)

### Temporary workaround:
- copy and paste the negative sign from somewhere else

### Possible long term solution:
- Putting a negative sign next to the input and ensure the input is always converted to negative value

p/s: this is my first ever issue/post so I apologize in advanced if I missed something, love your product!

**Comment by Chaphasilor** [comment]
Thanks for the report! We recently had a similar problem where the decimal point was missing, seems like I'll have to explicitly add the negative sign to the keyboard as well. Hopefully that's possible.

The current value of +1 isn't a huge problem though, since it works like the following:

- For each track, the server calculates the gain (change of volume) needed to bring all tracks to a reference level, which is -18 LUFS (*loudness units full-scale*)
- On iOS, Finamp now calculates the volume based on the configured base gain and the current track (or album) gain from the server. So if the track has a gain of -6.7 dB, and the base gain is -2.5 dB, the resulting gain applied to the volume will be -9.3 dB.

Now, if there's a track that is really quiet, the track gain will be *positive*, since in that case the volume needs to be increased. The base gain here essentially sets a limit for how much quiet tracks can be boosted by artificially limiting the volume using the base gain.  
However, because the reference level of -18 LUFS is rather low, there should be only very few tracks that actually have a positive gain. And for those tracks, they simply appear quieter than the other tracks, like they did before (but less so, since the louder tracks have been decreased in volume). So it's not a huge deal either.

I suggest you play around with positive base gains, and keep an eye on the metadata on the player screen. At the end, there should be a value in dB that shows the applied gain. If that value is positive, or is a negative, but smaller absolute value than your configured gain, the track will end up quieter than it should be. If that doesn't happen too frequently, it should work fine for you!

Hopefully this explanation wasn't too technical or confusing.  
Let me know if you have any questions, and I'll try to get that negative sign fixed!

**Comment by RantoPhantom** [comment]
Thanks for the answer! After messing around for a bit I think I know the culprit of most of the problems: Jellyfin on my server is still on 10.8.13 hence why I couldn't find the db metadata like you said

<img src="https://github.com/jmshrv/finamp/assets/64245707/149ba5bf-4c55-4331-a432-d3b3087859b8" styles="width: 50%; height: 50%;">

This also explains why the base gain adjustments go haywire when using positive numbers (on 100db even on the lowest volume, the speakers were booming, quite the mistake on my end lol)

<img src="https://github.com/jmshrv/finamp/assets/64245707/e7e357ed-e6f7-40f6-89e5-a0325d3cb010" styles="height:50%; width=50%;">

I'll pull Jellyfin 10.9 later in the day to see if this fixes things. Thanks for the informative  answer!

**Comment by Chaphasilor** [comment]
Haha yeah putting in 100 dB essentially means everything is at max volume, unless it's veeery quiet to begin with. I've now added the fix to get the negative sign to show up on the keyboard, so that'll get fixed with the next update!

Let me know how it goes with the new server version. Here's also a few steps you should take after upgrading:

1. Go to the admin dashboard on your server (menu at top left, then "Dashboard"), then to libraries
2. Click on your music library
3. Make sure that "Enable LUFS scan" is enabled, then click "Ok"
4. Click the three dots button on your music library card
5. Select "Scan library", then "Refresh"
   - This will try to find lyrics (both embedded and as separate `.lrc` files) within your library
6. If you have multiple music libraries, repeat steps 2-5 for all of them
7. After the scan is completed, scroll down the left sidebar and select "Scheduled Tasks"
8. In the "Library" section, click on the play icon for the "Audio Normalization" task
   - This will scan and extract the gain information for volume normalization
9. Now, open Finamp on your phone and go to the Downloads screen (menu button in upper left corner, then "Downloads")
10. On the downloads screen, click on the repair button (there are three buttons at the top right, it's the middle one with the screendriver and wrench icon)
    - This will make Finamp load all new data from the server, including lyrics and volume gain information, so that it's **available in offline mode**

**Comment by RantoPhantom** [comment]
After I updated my Jellyfin server to 10.9.1 and re-downloaded the songs, everything is working normally now.

Normalized metadata is showing correctly:
<img src="https://github.com/jmshrv/finamp/assets/64245707/905accf7-2857-4b8c-affe-9b70225fa968" styles="height:50%;width:50%;">

And setting Base Gain to 100 no longer maxed out the volume! Thanks for the kind and informative answers, I'll close this issue now!
