### ISSUE TITLE
[Redesign] Limit queue to current library

### ISSUE THREAD

**Issue by jgoguen** [jmshrv/finamp#732]
The redesign has changed the queue behaviour, with no way I’m seeing to turn it off. Previously, choosing a song from the track list would play that one track only, and shuffling from the track list would shuffle all songs from that library only. In the redesign, selecting a track from the track list populates the queue with all track from all libraries.

Two change requests because of this:

- Allow restricting all operations to the current library only. Whether as a setting or by adding an “All Libraries” virtual library to the library list isn’t terribly important, but a setting to force Finamp to restrict itself to the current library would be preferable.
- Some way to stop playing at the end of X songs. Previously I could just add 2 or 3 songs to the queue and that would be all that played. Now there is a sleep timer, but it’s limited to a length of time. Either add an option to stop after a number of tracks (along with limiting to the current library only) or allow me to clear the queue entirely and manually add tracks to it.

**Comment by Chaphasilor** [comment]
Okay, so what's happening here is that up until now, the redesign started what's known as an *Instant Mix* for the selected track. That is a feature provided by the server that will return somewhat-related tracks, based on genre.  
However, instant mixes don't currently support limiting the mix to a specific library, and that's the behavior you're seeing.  
This pattern of the Jellyfin server bot supporting features to be limited to a specific library is quite prevalent sadly, it also happens when loading artists and genres.

With the latest release (0.9.7), I added an option (settings > Interactions > "Start Instant Mixes for Individual Tracks") that you can turn off to get the same behavior as in the non-redesign version.  
I hope that resolves your issue!

Also, it is still possible to just add X tracks to the queue. Long-press the track you want to add and select "add to queue". You can also use "Add to Next Up" to prepend the track in front of the other tracks.

**Comment by jgoguen** [comment]
That does resolve the main issue! And with the option to not remember the play queue between app starts, I can now add specific tracks to the queue and tell Finamp to not repeat

> However, instant mixes don't currently support limiting the mix to a specific library

That's a shame, I do have one library where I'd like to be able to select one track to begin with and then shuffle all other tracks from that library. However, if the Shuffle All button could respect Next Up that would do it; I could add the track I want to start with to Next Up, press Shuffle All, and Finamp would play Next Up before moving on to the queue. Or if Shuffle All could have a long-press option to "shuffle all to queue", that would work.

**Comment by Chaphasilor** [comment]
The "shuffle all to queue" might be an option down the road. For now, you could first shuffle all and *then* add the track to next up. It will end up being in the queue twice, but I don't know if that's an issue for you. The other possibility is to shuffle all, then find the track in the queue, jump to it, and then toggle shuffle off and on again. That will shuffle all tracks to come after the current track.

I'll close this since the main issue has been resolved, and try to keep your request in mind for the future :)
