### ISSUE TITLE
0.9.8: Error on network change - Have to fully quit and start app again

### ISSUE THREAD

**Issue by jenshenk** [jmshrv/finamp#804]
Hi,
I'm using Finamp since a week now and it really added a lot of joy when I'm out and about! As an old millennial I also love the hint at my very very first media player :) 
One small issue, however, keeps bugging me: I'm using Finamp at home via Wifi and outside via the mobile network and vpn to my home network. When I'm leaving home and loosing contact with my wifi (vpn already started) finamp just shows me a connection error and the only way to fix it is to fully quit the app and start it again. Would it be possible to have some form of reload button in the sidebar or make finamp trying to connect again automatically? Thanks in advance for any improvement on this!

**Comment by Chaphasilor** [comment]
Hey, thanks for the feedback!

Where exactly are you getting this error? And after it occurs, does playback actually stop after some time?

Normally, Finamp should just go ahead and load the data and media over the new connection.  
The error notification towards the bottom of the screen can be dismissed by swiping/flinging it left or right, but might not go away on it's own, since it's an error notification. But that doesn't mean that the error is still present, it just happened once, at some point.

If you have persistant connection errors you can also normally pull down a the top of each tab to refresh, but that is currently not working in beta version 0.9.8. As an alternative, you can toggle offline mode on and then off again, that should reset things.


Also, are you using the beta version? The current stable version is 0.6.23, the beta is 0.9.8. There are many improvements in the beta that are worth checking out, but it is still a work-in-progress :)

**Comment by jenshenk** [comment]
Thanks for your quick response! I'm on the also really cool looking beta now and I think switching to offline mode and back again is a great tip. Funny enough, I prevented this from happening by just switching off wifi before leaving the house and make sure it works but it seems it now also works without needing to do that. If I haven't connected via VPN I get an error with a vibration (nice touch!) and upon connecting via vpn another vibration and it just works. Great! I'll keep monitoring this but I just tried a couple of times and it seems to work now. 

I don't know what your feature roadmap is but what I would really like is some form of Welcome overview, that could e.g. list latest added, last played albums/tracks etc .... any plans for this? That would pretty much make finamp perfect for me :) Thanks for all the effort you put into this!

**Comment by Chaphasilor** [comment]
Great, I'm glad that the beta improved it for you! As I said, there's currently a bug with the pull-to-refresh gesture, normally that would also do a hard refresh, same as toggling offline mode. That will work again with the next beta update!

And yes, a home screen with quick access to recents and latest media is definitely planned! If you're interested, you can give #220 a read, there are a few design mockups in there. But it's a long read ^^

**Comment by Chaphasilor** [comment]
Btw, the pull-to-refresh bug should now be fixed. Do you still have any issues?

**Comment by jenshenk** [comment]
Hi, thanks for the update! I have one very rare situation in one parking garage where my phone is jumping in and out of reception but toggling the offline mode fixes it once I'm outside again - besides that I didn't encounter any issues anymore! Gonna try pull to refresh the next time I'm there, thanks for checking in!

**Comment by Chaphasilor** [comment]
Awesome! I'll close this then, let me know if it should still be an issue!
