### ISSUE TITLE
[0.9.9] Playlists are not loading

### ISSUE THREAD

**Issue by KomGiann** [jmshrv/finamp#830]
Hello , I'd like to report that Playlist ( existing or new ) , show zero songs inside when accessed . For example , I have organized my library into playlists both on the Jellyfin platform and in Finamp but after close and reopen app the playlist contains 0 songs

**Comment by kuflierl** [comment]
No Repro, would you mind sharing the following to make it easier to chase down the problem:
Device: OS, OS version, Hardware
Server: Server OS, Server version, Notable Plugins

**Comment by Chaphasilor** [comment]
@KomGiann this could be a permission issue. Since Jellyfin 10.9, playlists are not accessible by all users anymore. Can you see the playlists in the official Jellyfin app, using the same account? 🤔

**Comment by Chaphasilor** [comment]
I just read in Symfonium's release notes about a fix regarding playlists after an "undocumented change". I'll try asking the server devs about it :)

**Comment by Chaphasilor** [comment]
In the Symfonium discussion it is mentioned that the playlists were returned with the wrong type (`Unknown` instead of `Playlist`). But on my 10.9.11 server the type is reported correctly, and Finamp can see the playlists just fine. So if you still have issues with that, I'd recommend making sure your Jellyfin server is up to date.  

I'll close the issue for now, but if it turns out that this is still an issue and you can provide some additional info for debugging, feel free to let me know!
