### ISSUE TITLE
Is it possible to modify finamp logo for my own app？

### ISSUE THREAD

**Issue by peerless2012** [jmshrv/finamp#971]
I develop a app for other platform, to prevent jellyfin logo copyright, i need to create a different logo , but i am not a designer, it's easy to copy and modify your app logo. 
I want to know, if  I can do this or not, and if this logo is protected by copyright.

**Comment by peerless2012** [comment]
My project is also a jellyfin client for other platform, I want to reuse the left side of your logo, and replace the center by audio or video icon, to fit my FinVideo or FinMusic app。

**Comment by jmshrv** [comment]
That sounds like the icon would end up very similar to Finamp, which may not be the best for your users. It makes sense that Finamp "remixes" the Jellyfin icon since Finamp is directly related to Jellyfin, but your app won't be directly related to Finamp.

Finamp was very lucky in that someone decided to make its icon relatively early on (the first versions shipped without an icon), perhaps your apps will be just as lucky :)

**Comment by peerless2012** [comment]
Thanks, I will make my own icon, same like finamp to jellyfin, I will refer finamp idea and design my icon. And the icon will be different to finamp.

**Comment by Chaphasilor** [comment]
Awesome, good luck! And let us know when we can try out your app! 😁
