### ISSUE TITLE
[Redesign] Very aggressive buffering (or maybe wasting data)

### ISSUE THREAD

**Issue by dogtopus** [jmshrv/finamp#986]
I noticed that the network activity didn't stop after one song is fully buffered. The buffering also didn't seem to stop even after Finamp consumed more than 3x the amount of the data required to pull the first song so I suspect that it's trying to pull the entire queue. Although if I try to switch to next tracks Finamp would seemingly discard the buffer after only 2 switches, wasting the data it uses to pull the songs.

I'm running Finamp 0.9.12.

**Comment by Chaphasilor** [comment]
Yeah I chose 10 minutes as the default to be tolerant against spotty connections while driving or commuting. I was annoyed that playback always paused on my daily commute with the stable version (or other media players).  
Pre-caching a certain number of track isn't easy sadly, but we'll probably change the buffer size to be in bytes instead of seconds, because high-quality audio (like FLAC) will consume tons of RAM otherwise.

**Comment by dogtopus** [comment]
I don't think pre-caching # of tracks is necessary. Ideally allowing the user to set the buffer size separately for metered and unmetered connections, either by data size or time would be good IMO. If you want something fancier maybe also temporarily allow more aggressive buffering on spotty connections as well.
